trigger:
- master

variables:
  buildConfiguration: Release

jobs:
  - job: DynatraceExtension
    displayName: Install/Update Dynatrace Extension
    pool:
      vmImage: windows-2019
    steps:
    - task: PowerShell@2
      inputs:
        targetType: inline
        script: 'az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(servicePrincipalTenant)'
    - task: PowerShell@2
      inputs:
        filePath: dynatrace-extension.ps1
        arguments: '-subscription "$(azureSubscription)" -resourceGroup "$(azureResourceGroup)" -appName "$(appName)" -environmentId "$(dynatraceEnvId)" -apiToken "$(dynatracePaasToken)"'

  - job: AppService
    displayName: Deploy to App Service
    dependsOn: DynatraceExtension
    pool:
      vmImage: windows-2019
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: Package
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
    - task: PublishBuildArtifacts@1
      displayName: Publish
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: appServiceMVC
    - task: AzureWebApp@1
      displayName: Deploy
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        appType: webAppLinux
        appName: '$(appName)'
        package: '$(System.ArtifactsDirectory)/**/*.zip'
